CREATE TABLE IF NOT EXISTS users (
  usr_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  usr_username         VARCHAR(32) NOT NULL UNIQUE,
  usr_password         VARCHAR(255) NOT NULL,
  usr_name             VARCHAR(32) NOT NULL,

  usr_created_at   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS categories (
  ctg_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  ctg_name             VARCHAR(64) NOT NULL UNIQUE,

  ctg_created_at   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS books (
  bks_id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  bks_ctg_id       INTEGER NOT NULL REFERENCES categories(ctg_id) ON DELETE CASCADE,

  bks_name             VARCHAR(64) NOT NULL UNIQUE,
  bks_author           VARCHAR(128) NOT NULL,
  bks_publisher        VARCHAR(128) NOT NULL,
  bks_year             INTEGER NOT NULL,
  bks_description      TEXT NOT NULL,
  bks_price            INTEGER NOT NULL,
  bks_url              TEXT NOT NULL,

  bks_created_at   TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

